name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          set -e
          cd ~/humbub || git clone https://github.com/alfarmer/humbub.git && cd humbub
          git pull origin main
          docker-compose down -v --remove-orphans
          docker-compose up -d --build
